config/routes.rb
I3s::Application.routes.draw do

  resources :delegation_assignments

  resources :roles

  resources :lists

  resources :countries

  devise_for :users, :controllers => {:confirmations => 'confirmations'}

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :users do
    put :update_password, :on => :member
  end

  resources :assignments
  
  resources :delegates
  
  resources :schools do
    resources :delegates
  end

  resources :committees

  resources :conferences do
    resources :lists
    resources :committees
    resources :schools
    resources :delegation_assignments
  end

  match 'requestaccess' => 'requestaccess#new', :as => 'requestaccess', :via => :get
  match 'requestaccess' => 'requestaccess#create', :as => 'requestaccess', :via => :post

    root :to => 'conferences#index'

end

app/models/list.rb
class List < ActiveRecord::Base

	#Relationships
	belongs_to :conference

	has_many :committees
	
	has_many :delegation_assignments, :dependent => :destroy
	has_many :countries, :through => :delegation_assignments
	has_many :schools, :through => :delegation_assignments

	#Scopes
	scope :btaconference, lambda{ |btaconference| joins(:conference).where(:conferences => {:conference_title => btaconference}) }
	scope :btacountry, lambda{ |btacountry| joins(:countries).where(:countries => {:id => btacountry}) }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  #  @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
  #  @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
  #  @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  # def create
  # #  @list = List.new(params[:list])

  #   respond_to do |format|
  #     if @list.save
  #       format.html { redirect_to @list, notice: 'List was successfully created.' }
  #       format.json { render json: @list, status: :created, location: @list }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @list.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
  #  @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  # def destroy
  # #  @list = List.find(params[:id])
  #   @list.destroy

  #   respond_to do |format|
  #     format.html { redirect_to lists_url }
  #     format.json { head :no_content }
  #   end
  # end

  def create
    @conference = Conference.find(params[:conference_id])
    @list = @conference.lists.create(params[:list])
    redirect_to conference_path(@conference)
  end

  def destroy
    @conference = Conference.find(params[:conference_id])
    @list = @conference.lists.find(params[:id])
    @list.destroy
    redirect_to conference_path(@conference)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_countries_checkboxes.html.erb
<% for country in Country.all  %>
     <%= check_box_tag "list[country_ids][]", country.id, @conference.lists.include?(country) %>
     <%= country.country_name %>
     <br />
  <% end  %>

app/views/lists/_form.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<section id="forms">
    <div class="span12">
      <%= render 'layouts/messages' %>
      <div class="form-horizontal well">
<%= form_for([@conference, @conference.lists.build]) do |f| %>

<div class="control-group">
  <%= f.label :list_name, :class => "control-label" %>
  <div class="controls">
    <%= f.text_field :list_name %>
  </div>
  </div>
  <div class="control-group">
    <%= f.label :countries, :class => "control-label" %><br />
      <div class="controls checkboxlist">
      <% for country in Country.all  %>
      <label class="checkbox">
          <%= check_box_tag "list[country_ids][]", country.id, @conference.lists.include?(country) %>
          <%= country.country_name %>
        </label>
      <% end  %>
    </div>
  </div>
  
  <div class="control-group">
        <div class="controls">
          <%= f.submit "Create Country List", :class => "btn btn-primary"%>
  </div>
  </div>
<% end %>


    </div>
  </div>

</section>

app/views/lists/_list.html.erb
<table class="table" style="margin-bottom:0px;">
<tbody>
<td style="width: 130px;"><%= link_to list.list_name, list_path(list) %></td>
<td><%= link_to image_tag('trash.png'), [list.conference, list], :confirm => 'Are you sure you want to delete this country list?', :method => :delete %></td>
</tbody>
</table>

app/views/lists/_list_of_countries.html.erb
<p>
	<b><%= pluralize(@list.countries.size, 'Country') %></b><br />
	<ul>
		<% for country in @list.countries %>
			<li><%= link_to((country.country_name), country_path(country)) %></li>
		<% end  %>
	</ul>
</p>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container" style="padding-left:20px; padding-right:20px; background-color:white;">


<ul class="nav nav-tabs" style="padding-top:20px;">
    <% if current_user.role? "System Admin" %>
    <li class="dropdown">
      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
        Users
        <b class="caret"></b>
      </a>

      <ul class="dropdown-menu">
        <li><%= link_to "All Users", users_path %></li>
        <li><%= link_to "Roles", roles_path %></li>
      </ul>
    </li>
    <% else %>
    
    <li><%= link_to "Users", users_path %></li>
    <% end %>
		<li><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown active">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li><%= link_to "Committees", committees_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>

		
	</li>
</ul>
<h2>Custom Country Lists</h2>
  
  <br/>

<div class="well form-inline">

<table class="table table-striped">
	<thead>
		<tr>
			<th>List name</th>
			<th>Conference</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @lists.each do |list| %>
		<tr>
			<td><%= link_to list.list_name, list %></td>
			<td><%= list.conference.conference_title %></td>
			<td><%= link_to image_tag('edit.png'), edit_list_path(list) %></td>
			<td><%= link_to image_tag('trash.png'), list, confirm: 'Are you sure you want to delete this list? This cannot be undone.', method: :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
<br />
<hr>
<p ALIGN="RIGHT"> <i class="icon-chevron-up"></i> <a href="#top">Back to Top</a></p>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container" style="padding-top:70px;">
<div class="span7 offset2">
<h1>List Information</h1>

</div>
</div>
<div class="container">

<section id="forms">
    <div class="span7 offset2">
      <%= render 'layouts/messages' %>
      <div class="form-horizontal well">
<p>
  <b>List name:</b>
  <%= @list.list_name %>
</p>

<%= render :partial => 'list_of_countries' %>
      </div>
      <%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>
  </div>
</section>
</div>