config/routes.rb
I3s::Application.routes.draw do

  resources :delegation_assignments

  resources :roles

  resources :lists

  resources :countries

  devise_for :users, :controllers => {:confirmations => 'confirmations'}

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :users do
    put :update_password, :on => :member
  end

  resources :assignments
  
  resources :delegates
  
  resources :schools do
    resources :delegates
  end

  resources :committees

  resources :conferences do
    resources :lists
    resources :committees
    resources :schools
    resources :delegation_assignments
  end

  match 'requestaccess' => 'requestaccess#new', :as => 'requestaccess', :via => :get
  match 'requestaccess' => 'requestaccess#create', :as => 'requestaccess', :via => :post

    root :to => 'conferences#index'

end

app/models/conference.rb
class Conference < ActiveRecord::Base

  #Attributes
  attr_accessible :conference_title, :start_date, :end_date, :host, :venue, :conference_details, :latitude, :longitude, :user_id, :is_active
  geocoded_by :venue
  after_validation :geocode, :if => :venue_changed?

  #Relationships
  belongs_to :user

	has_many :committees, :dependent => :destroy
  accepts_nested_attributes_for :committees, :allow_destroy => :true
	
  has_many :lists, :dependent => :destroy
	accepts_nested_attributes_for :lists, :allow_destroy => :true

  has_many :schools, :dependent => :destroy
  accepts_nested_attributes_for :schools, :allow_destroy => :true

  has_many :delegation_assignments, :dependent => :destroy
  accepts_nested_attributes_for :delegation_assignments, :allow_destroy => :true
	
	#Validations
  validates :conference_title, :presence => true, :length => { :minimum => 3 }
  validates_presence_of :host
  validates_presence_of :venue
  validates_presence_of :conference_details
  validates_presence_of :start_date
  validates_presence_of :end_date
  validate :start_must_be_before_end_date
  validate :start_date_not_in_past

  #Methods
  def start_must_be_before_end_date
    errors.add(:start_date, "Must be before end time") unless
    self.start_date <= self.end_date
  end

  def start_date_not_in_past
    errors.add(:start_date, "must not be in past") unless 
    self.start_date > Date.current
  end 

	def duration
    "#{start_date.strftime('%b %d, %Y')} - #{end_date.strftime('%b %d, %Y')}"
  end

end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /conferences
  # GET /conferences.json
  def index
    if current_user.role? :"System Admin"
      @conferences = Conference.all
    else
      if current_user.role? :"Conference Manager"
        @conferences = Conference.where("user_id = ?", current_user.id)
      else
        @conferences = Conference.where("is_active = ?", true)
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }

      @search = Conference.search(params[:search])
      if current_user.role? :"System Admin"
        @conferences = @search.all
      else
        if current_user.role? :"Conference Manager"
          @conferences = @search.where("user_id = ?", current_user.id)
        else
          @conferences = @search.where("is_active = ?", true)
        end
      end
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
        UserMailer.new_conference_msg(@conference).deliver
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container">

<section id="forms">
    <div class="span7 offset2">
      <%= render 'layouts/messages' %>
      <div class="form-horizontal well">				
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>


      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <legend>Conference Details</legend>

	<div class="control-group">
    <%= f.label :assign_conference_manager , :class => "control-label" %>
		<div class="controls">
    <%= f.collection_select :user_id, User.with_role("Conference Manager"), :id, :fullname, :prompt => "Select Conference Manager" %>
    <p class="help-block">(or add a <%= link_to "new Conference Manager", new_user_path(@user), :target => "_blank" %>)</p>
  		</div>
</div>



<div class="control-group">
    <%= f.label :conference_title , :class => "control-label" %>
	<div class="controls">
    <%= f.text_field :conference_title %>
  	</div>
</div>

<div class="control-group">
    <%= f.label :start_date , :class => "control-label" %>
	<div class="controls">
    <%= f.text_field :start_date, :placeholder => "dd/mm/yyyy", :databehaviour => "datepicker"%>
  </div>
</div>


<div class="control-group">
    <%= f.label :end_date , :class => "control-label" %>
	<div class="controls">

    <%= f.text_field :end_date, :placeholder => "dd/mm/yyyy", :databehaviour => "datepicker"%>
  </div>
</div>



<div class="control-group">
    <%= f.label :host_school_or_organization, :class => "control-label" %>
	<div class="controls">

    <%= f.text_field :host %>
  </div>
</div>



<div class="control-group">
    <%= f.label :venue , :class => "control-label" %>
	<div class="controls">

    <%= f.text_field :venue %>
  </div>
</div>



<div class="control-group">
    <%= f.label :conference_details , :class => "control-label" %>
	<div class="controls">

    <%= f.text_area :conference_details, :size => "30x10" %>
  </div>
</div>



<div class="control-group">
    <%= f.label :Conference_Status , :class => "control-label" %>
	<div class="controls">
    <label class="checkbox">
    <%= f.check_box :is_active, :id=>"optionsCheckbox" %>Active
  </label>
  </div>
</div>



</br>
<div class="control-group">
            <div class="controls">
              <%= f.submit "Create Conference", :class => "btn btn-primary"%>
              <%= link_to "Cancel", root_path, :class => "btn" %>
            </div>
          </div>

<% end %>

</div>
    </div>
  </div>
</section>

app/views/conferences/edit.html.erb
<div class="container" style="padding-left:20px; padding-right:20px; background-color:white;">

<ul class="nav nav-tabs" style="padding-top:20px;">
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Users
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "All Users", users_path %></li>
				<li><%= link_to "Roles", roles_path %></li>
			</ul>
		</li>
		<li class="active"><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li><%= link_to "Committees", committees_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>


<div class="span7 offset2">
	<h2>Edit Conference</h2>
</div>
<%= render 'form' %>
</div>



<ul class="pager">
  <li>	<%= link_to 'Back to users', users_path %></li>
</ul>

app/views/conferences/index.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container" style="padding-left:20px; padding-right:20px; background-color:white;">

<% if !current_user.role? :"MUN Director" %>
	<ul class="nav nav-tabs" style="padding-top:20px;">
    <% if current_user.role? "System Admin" %>
    <li class="dropdown">
      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
        Users
        <b class="caret"></b>
      </a>

      <ul class="dropdown-menu">
        <li><%= link_to "All Users", users_path %></li>
        <li><%= link_to "Roles", roles_path %></li>
      </ul>
    </li>
    <% else %>
    
    <li><%= link_to "Users", users_path %></li>
    <% end %>
		<li class="active"><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li><%= link_to "Committees", committees_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>
<% else %>
<ul class="nav nav-tabs" style="padding-top:20px;">
		<li class="active"><%= link_to "Conferences", conferences_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>
<% end %>
<div class="pull-right">
	<%= form_for @search, :url => conferences_path, :html => {:method => :get} do |f| %>
		<%= f.text_field :conference_title_contains, :class => "navbar-search form-inline input-medium search-query", :placeholder => "Search by title" %>
	<% end %>
</div>
	<h2>Conferences</h2>
	<% if current_user.role? "System Admin" %>
	<a href="/conferences/new" class="btn pull-left"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Create New Conference</a>
	<% end %>
	<br/><br/>

<div class="well form-inline">
<table class="table table-striped">
	<thead>
		<tr>
			<th>Conference</th>
			<th>Conference Manager</th>
			<th>Session</th>
			<% if current_user.role? "System Admin" %>
			<th></th>
			<th></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @conferences.each do |conference| %>
		<tr>
			<td><%= link_to conference.conference_title, conference %><br/>
			<%= conference.duration %><br/>
			<%= conference.venue %></td>
			<td><%= conference.user.fullname %></td>
			<td><% if conference.is_active? %>
				<p style="color: #47CB2A; margin-bottom: 0;">Active</p>
				<% else %>
				<p style="color: #EB0301; margin-bottom: 0;">Inactive</p>
				<% end %>
			</td>
			<% if current_user.role? "System Admin" %>
			<td><%= link_to image_tag('edit.png'), edit_conference_path(conference) %></td>
			<td><%= link_to image_tag('trash.png'), conference, confirm: 'Are you sure you want to delete this conference? This cannot be undone.', method: :delete %></td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

<br/>
<hr>

<p ALIGN="RIGHT"> <i class="icon-chevron-up"></i> <a href="#top">Go to Top</a></p>
</div>

app/views/conferences/new.html.erb
<div class="container" style="padding-left:20px; padding-right:20px; background-color:white;">

<ul class="nav nav-tabs" style="padding-top:20px;">
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Users
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "All Users", users_path %></li>
				<li><%= link_to "Roles", roles_path %></li>
			</ul>
		</li>
		<li class="active"><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li><%= link_to "Committees", committees_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>


<div class="span7 offset2">
	<h2>Create New Conference</h2>
</div>
<%= render 'form' %>
</div>



<ul class="pager">
  <li>	<%= link_to 'Back to conferences', conferences_path %></li>
</ul>

app/views/conferences/show.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<!-- Conference
================================================== -->
<div class="container">
<!--when click on conference name-->
<section id="conference">
	
	<% if current_user.role? "System Admin" %>

<ul class="nav nav-tabs" style="padding-top:20px; background-color:white; margin-bottom: 0px;">
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Users
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "All Users", users_path %></li>
				<li><%= link_to "Roles", roles_path %></li>
			</ul>
		</li>
		<li class="active"><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li><%= link_to "Committees", committees_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>
	
	<% end %>
	
    <div class="row-fluid">
      <div class="span12 well" style="margin-top:20px; height:auto;">
        <h1><%= @conference.conference_title %></h1>
        <h3 style="color: #39b1c6;"><%= @conference.start_date.strftime('%B %e, %Y') %> - <%= @conference.end_date.strftime('%B %e, %Y') %></h3>
        <h4>Hosted by <%= @conference.host %></h4>
                <% if current_user.role? "System Admin" %>
                <div style="margin-top:30px;">
      <%= link_to image_tag('edit.png'), edit_conference_path(@conference) %>&nbsp;&nbsp;<%= link_to 'Edit Conference', edit_conference_path(@conference) %>
        &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to image_tag('trash.png'), @conference, confirm: 'Are you sure you want to delete this conference? This cannot be undone.', method: :delete %>&nbsp;&nbsp;<%= link_to 'Delete Conference', @conference, confirm: 'Are you sure you want to delete this conference? This cannot be undone.', method: :delete %>

    </div>
      <% end %>
      </div>
    </div>

<% if current_user.role? "Conference Manager" %>
  <div class="row-fluid">
    <div class="span3 well">
      <h5>STEP 1&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>Country Lists</h3>
      <p>
        <%= render @conference.lists %>
        <a href="#createlist" role="button" class="btn" data-toggle="modal" style="margin-top: 10px;"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Create Country List</a>
      </p>

      <div id="createlist" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Create Country List</h3>
        </div>
        <div class="modal-body">
          <%= render 'lists/form' %>
        </div>
      </div>
    </div>
    <div class="span3 well">
      <h5>STEP 2&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>Committees</h3>
      <p>
        <%= render @conference.committees %>
        <a href="#createcommittee" role="button" class="btn" data-toggle="modal" style="margin-top: 10px;"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Create Committee</a>
      </p>

      <div id="createcommittee" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Create Committee</h3>
        </div>
        <div class="modal-body">
          <%= render 'committees/form' %>
        </div>
      </div>
    </div>
    
    
    
     <div class="span3 well">
      <h5>STEP 3&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>MUN Directors</h3>
      <p>
      <a href="/users/new" role="button" class="btn" style="margin-top: 10px;"><i class="icon-tasks" style="padding-top:2px;"></i>&nbsp;Add MUN Directors</a>
    </p>
    </div>

    
    <div class="span3 well">
      <h5>STEP 4&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>Schools</h3>
      <p>
      <a href="/delegation_assignments" role="button" class="btn" style="margin-top: 10px;"><i class="icon-tasks" style="padding-top:2px;"></i>&nbsp;Assign Schools</a>
    </p>
    </div>
  </div>
<% end %>

<% if current_user.role? "MUN Director" %>
  <div class="row-fluid">
    <div class="span4 well">
      <h5>STEP 1&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>Register School</h3>
      <p>
        <%= render @conference.schools %>
        <a href="#createschool" role="button" class="btn" data-toggle="modal" style="margin-top: 10px;"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Register School</a>
      </p>

      <div id="createschool" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Register School</h3>
        </div>
        <div class="modal-body">
          <%= render 'schools/form' %>
        </div>
      </div>
      
    </div>
    <div class="span4 well">
      <h5>STEP 2&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>Assign Delegates</h3>
        <p>
        <a href="/schools" role="button" class="btn" style="margin-top: 10px;"><i class="icon-tasks" style="padding-top:2px;"></i>&nbsp;Assign Delegates</a>
      </p>
    </div>
  
  
    <div class="span4 well">
      <h5>STEP 3&nbsp;<i class="icon-chevron-right" style="padding-top:2px;"></i></h5>
      <h3>Confirm Submission</h3>
      <p>
      <a href="mailto:teami3s.2012@gmail.com?Subject=School%20Registers&Body=Delegates%20from%20my%20school%20have%20been%20registered%20for%20the%20conference.%20Thank%20you." role="button" class="btn" style="margin-top: 10px;"><i class="icon-envelope-alt" style="padding-top:2px;"></i>&nbsp;Send Email</a>
    </p>
    </div>
  </div>
<% end %>

  <div class="row-fluid">
    <div class="span6 well">
      <h3>Conference Details</h3>
      <p><%= @conference.conference_details %></p>

    </div>
    <div class="span6 well">
      <h3>Venue</h3>
      <p><%= @conference.venue %></p>
      <p><%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@conference.latitude}%2C#{@conference.longitude}" %></p>

    </div>
  </div>
</section>
<% if current_user.role? "System Admin" %>
  <div class="row-fluid">
    <div class="span3 well">
      <h3>Country Lists</h3>
      <p>
        <%= render @conference.lists %>
        <a href="#createlist" role="button" class="btn" data-toggle="modal" style="margin-top: 10px;"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Create Country List</a>
      </p>

      <div id="createlist" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Create Country List</h3>
        </div>
        <div class="modal-body">
          <%= render 'lists/form' %>
        </div>
      </div>
    </div>
    <div class="span3 well">
      <h3>Committees</h3>
      <p>
        <%= render @conference.committees %>
        <a href="#createcommittee" role="button" class="btn" data-toggle="modal" style="margin-top: 10px;"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Create Committee</a>
      </p>

      <div id="createcommittee" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Create Committee</h3>
        </div>
        <div class="modal-body">
          <%= render 'committees/form' %>
        </div>
      </div>
    </div>
    
    
    
     <div class="span3 well">
      <h3>MUN Directors</h3>
      <p>
      <a href="/users/new" role="button" class="btn" style="margin-top: 10px;"><i class="icon-tasks" style="padding-top:2px;"></i>&nbsp;Add MUN Directors</a>
    </p>
    </div>

    
    <div class="span3 well">
      <h3>Schools</h3>
      <p>
      <a href="/delegation_assignments" role="button" class="btn" style="margin-top: 10px;"><i class="icon-tasks" style="padding-top:2px;"></i>&nbsp;Assign Schools</a>
    </p>
    </div>
  </div>
<% end %>
<% if current_user.role? "System Admin" %>
  <div class="row-fluid">
    <div class="span4 well">
      <h3>Register School</h3>
      <p>
        <%= render @conference.schools %>
        <a href="#createschool" role="button" class="btn" data-toggle="modal" style="margin-top: 10px;"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Register School</a>
      </p>

      <div id="createschool" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Register School</h3>
        </div>
        <div class="modal-body">
          <%= render 'schools/form' %>
        </div>
      </div>
      
    </div>
    <div class="span4 well">
      <h3>Assign Delegates</h3>
        <p>
        <a href="/schools" role="button" class="btn" style="margin-top: 10px;"><i class="icon-tasks" style="padding-top:2px;"></i>&nbsp;Assign Delegates</a>
      </p>
    </div>
  
  
    <div class="span4 well">
      <h3>Confirm Submission</h3>
      <p>
      <a href="mailto:teami3s.2012@gmail.com?Subject=School%20Registers&Body=Delegates%20from%20my%20school%20have%20been%20registered%20for%20the%20conference.%20Thank%20you." role="button" class="btn" style="margin-top: 10px;"><i class="icon-envelope-alt" style="padding-top:2px;"></i>&nbsp;Send Email</a>
    </p>
    </div>
  </div>
<% end %>
<hr>


<ul class="pager">
  <li>  <%= link_to 'Back to Conferences', conferences_path %></li>
</ul>

</div>
<script>