config/routes.rb
I3s::Application.routes.draw do

  resources :delegation_assignments

  resources :roles

  resources :lists

  resources :countries

  devise_for :users, :controllers => {:confirmations => 'confirmations'}

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :users do
    put :update_password, :on => :member
  end

  resources :assignments
  
  resources :delegates
  
  resources :schools do
    resources :delegates
  end

  resources :committees

  resources :conferences do
    resources :lists
    resources :committees
    resources :schools
    resources :delegation_assignments
  end

  match 'requestaccess' => 'requestaccess#new', :as => 'requestaccess', :via => :get
  match 'requestaccess' => 'requestaccess#create', :as => 'requestaccess', :via => :post

    root :to => 'conferences#index'

end

app/models/committee.rb
class Committee < ActiveRecord::Base
	
	#Relationships
	belongs_to :conference
	belongs_to :list
	has_many :delegates, limit: 2

	#Validations
	validates :committee_name, :presence => true, :length => { :minimum => 2 }
	validates :num_delegates, :presence => true
	validates :list_id, :presence => true

	#Scopes
	scope :btalist, lambda{ |btalist| joins(:list).where(:lists => {:id => btalist}) }
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @committees }
      
      
        	@search = Committee.search(params[:search])
          @committees = @search.all   # load all matching records

      
    end
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
  #  @committee = Committee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @committee }
    end
  end

  # GET /committees/new
  # GET /committees/new.json
  def new
  #  @committee = Committee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @committee }
    end
  end

  # GET /committees/1/edit
  def edit
  #  @committee = Committee.find(params[:id])
  end

  # POST /committees
  # POST /committees.json
  # def create
  # #  @committee = Committee.new(params[:committee])

  #   respond_to do |format|
  #     if @committee.save
  #       format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
  #       format.json { render json: @committee, status: :created, location: @committee }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @committee.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /committees/1
  # PUT /committees/1.json
  def update
  #  @committee = Committee.find(params[:id])

    respond_to do |format|
      if @committee.update_attributes(params[:committee])
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  # def destroy
  # #  @committee = Committee.find(params[:id])
  #   @committee.destroy

  #   respond_to do |format|
  #     format.html { redirect_to committees_url }
  #     format.json { head :no_content }
  #   end
  # end

  def create
    @conference = Conference.find(params[:conference_id])
    @committee = @conference.committees.create(params[:committee])
    redirect_to conference_path(@conference)
  end

  def destroy
    @conference = Conference.find(params[:conference_id])
    @committee = @conference.committees.find(params[:id])
    @committee.destroy
    redirect_to conference_path(@conference)
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_committee.html.erb
<table class="table" style="margin-bottom:0px;">
<tbody>
<td style="width: 130px;"><%= link_to committee.committee_name, committee_path(committee) %></td>
<td><%= link_to image_tag('trash.png'), [committee.conference, committee], :confirm => 'Are you sure you want to delete this committee?', :method => :delete %></td>
</tbody>
</table>

app/views/committees/_form.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<section id="forms">
    <div class="span12">
      <%= render 'layouts/messages' %>
      <div class="form-horizontal well">
<%= form_for([@conference, @conference.committees.build]) do |f| %>

  	<div class="control-group">
    <%= f.label :committee_name, :class => "control-label"  %>
<div class="controls">
    <%= f.text_field :committee_name %>
  </div>
</div>


  <div class="control-group">
    <%= f.label :Number_of_delegates, :class => "control-label"  %>
    <div class="controls">
    <%= f.number_field :num_delegates %>
</div>
  </div>

  <div class="control-group">
    <%= f.label :list_id, :class => "control-label" %>
        <div class="controls">
    <%= f.collection_select :list_id, List.where("conference_id = ?", @conference.id), :id, :list_name, :prompt => "Select Country List" %>
  </div>
  </div>

  <div class="control-group">
        <div class="controls">
          <%= f.submit "Create Committee", :class => "btn btn-primary"%>
  </div>
  </div>

<% end %>


		</div>
	</div>

</section>

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container" style="padding-left:20px; padding-right:20px; background-color:white;">

<ul class="nav nav-tabs" style="padding-top:20px;">
    <% if current_user.role? "System Admin" %>
    <li class="dropdown">
      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
        Users
        <b class="caret"></b>
      </a>

      <ul class="dropdown-menu">
        <li><%= link_to "All Users", users_path %></li>
        <li><%= link_to "Roles", roles_path %></li>
      </ul>
    </li>
    <% else %>
    
    <li><%= link_to "Users", users_path %></li>
    <% end %>
 
		<li><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li class="active"><%= link_to "Committees", committees_path %></li>
		<li><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>

		
	</li>
</ul>

<div class="pull-right">
	<%= form_for @search, :url => committees_path, :html => {:method => :get} do |f| %>
		<%= f.text_field :committee_name_contains, :class => "navbar-search form-inline input-medium search-query", :placeholder => "Search" %>
	<% end %>
</div>
	<h2>Committees</h2>
	
	<br/>

<div class="well form-inline">
<table class="table table-striped">
	<thead>
		<tr>
			<th>Committee name</th>
			<th>Number of delegates</th>
			<th>Conference</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @committees.each do |committee| %>
		<tr>
			<td><%= link_to committee.committee_name, committee %></td>
			<td><%= committee.num_delegates %></td>
			<td><%= committee.conference.conference_title %></td>
			<td><%= link_to image_tag('edit.png'), edit_committee_path(committee) %></td>
			<td><%= link_to image_tag('trash.png'), committee, confirm: 'Are you sure you want to delete this committee? This cannot be undone.', method: :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
<br/><hr>
<p ALIGN="RIGHT"> <i class="icon-chevron-up"></i> <a href="#top">Go to Top</a></p>

</div>

app/views/committees/new.html.erb
<h1>Add a new committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container" style="padding-top:70px;">
<div class="span7 offset2">
<h1>Committee Information</h1>
</div>
</div>
<div class="container">

<section id="forms">
    <div class="span7 offset2">
      <%= render 'layouts/messages' %>
      <div class="form-horizontal well">
<p>
  <b>Committee name:</b>
  <%= @committee.committee_name %>
</p>

<p>
  <b>Number of delegates:</b>
  <%= @committee.num_delegates %>
</p>

<p>
  <b>Country list:</b>
  <% for country in @committee.list.countries %>
    <li><%= link_to((country.country_name), country_path(country)) %></li>
  <% end  %>
</p>

<p>
  <b>Conference:</b>
  <%= @committee.conference.conference_title %>
</p>
      </div>
<%= link_to 'Edit committee', edit_committee_path(@committee) %> |
<%= link_to 'Back to committees list', committees_path %>
  </div>
</section>
</div>