config/routes.rb
I3s::Application.routes.draw do

  resources :delegation_assignments

  resources :roles

  resources :lists

  resources :countries

  devise_for :users, :controllers => {:confirmations => 'confirmations'}

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :users do
    put :update_password, :on => :member
  end

  resources :assignments
  
  resources :delegates
  
  resources :schools do
    resources :delegates
  end

  resources :committees

  resources :conferences do
    resources :lists
    resources :committees
    resources :schools
    resources :delegation_assignments
  end

  match 'requestaccess' => 'requestaccess#new', :as => 'requestaccess', :via => :get
  match 'requestaccess' => 'requestaccess#create', :as => 'requestaccess', :via => :post

    root :to => 'conferences#index'

end

app/models/school.rb
class School < ActiveRecord::Base

	#Attributes
	attr_accessible :user_id, :school_name, :school_address, :email, :max_students, :conference_id, :country_ids

	#Relationships
	belongs_to :conference
	belongs_to :user

	has_many :delegation_assignments
	has_many :countries, :through => :delegation_assignments
	has_many :lists, :through => :delegation_assignments

	has_many :delegates, :dependent => :destroy
	accepts_nested_attributes_for :delegates, :allow_destroy => :true

  	#Validations
	validates :school_name, :presence => true

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /schools
  # GET /schools.json
  def index
    
    if current_user.role? :"System Admin"
      @schools = School.all
    else
      @schools = School.where("user_id = ?", current_user.id)
    end

    respond_to do |format|
      format.html # index.html.erb
       format.xml { render :xml => @schools }
        format.xls { send_data @schools.to_xls, :filename => 'schools.xls' }
      format.json { render json: @schools }
	  
	   
      	@search = School.search(params[:search])
        @schools = @search.all   # load all matching records
        
    if current_user.role? :"System Admin"
        @schools = @search.all
      else
        @schools = @search.where("user_id = ?", current_user.id)
      end
     	  
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  #  @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
  #  @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
  #  @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  # def create
  # #  @school = School.new(params[:school])

  #   respond_to do |format|
  #     if @school.save
  #       format.html { redirect_to @school, notice: 'School was successfully created.' }
  #       format.json { render json: @school, status: :created, location: @school }
        
  #       # Provide a email confirmation if all is good...
		#     UserMailer.new_school_msg(@school).deliver
        
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @school.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
  #  @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  # def destroy
  # #  @school = School.find(params[:id])
  #   @school.destroy

  #   respond_to do |format|
  #     format.html { redirect_to schools_url }
  #     format.json { head :no_content }
  #   end
  # end

  def create
    @conference = Conference.find(params[:conference_id])
    @school = @conference.schools.create(params[:school])
    redirect_to conference_path(@conference)
    UserMailer.new_school_msg(@school).deliver
  end

  def destroy
    @conference = Conference.find(params[:conference_id])
    @school = @conference.schools.find(params[:id])
    @school.destroy
    redirect_to conference_path(@conference)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<section id="forms">
    <div class="span12">
      <%= render 'layouts/messages' %>
      <div class="form-horizontal well">
<%= form_for([@conference, @conference.schools.build]) do |f| %>

  <div class="control-group">
    <%= f.label :school_name, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :school_name %>
  </div>
  </div>
  
  <div class="control-group">
    <%= f.label :school_address, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :school_address %>
  </div>
</div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Register School", :class => "btn btn-primary"%>
  </div>
</div>
<% end %>
</div>
</div>
</section>

app/views/schools/_list_of_delegates.html.erb
<p>
	<b><%= pluralize(@school.delegates.size, 'Delegate') %></b><br />
	<ul>
		<% for delegate in @school.delegates %>
			<li><%= link_to((delegate.first_name), delegate_path(delegate)) %></li>
		<% end  %>
	</ul>
</p>

app/views/schools/_school.html.erb
<table class="table" style="margin-bottom:0px;">
<tbody>
<td style="width: 220px;"><%= link_to school.school_name, school_path(school) %></td>
<td><%= link_to image_tag('trash.png'), [school.conference, school], :confirm => 'Are you sure you want to delete this school?', :method => :delete %></td>
</tbody>
</table>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container" style="padding-left:20px; padding-right:20px; background-color:white;">

<% if !current_user.role? :"MUN Director" %>
<ul class="nav nav-tabs" style="padding-top:20px;">
    <% if current_user.role? "System Admin" %>
    <li class="dropdown">
      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
        Users
        <b class="caret"></b>
      </a>

      <ul class="dropdown-menu">
        <li><%= link_to "All Users", users_path %></li>
        <li><%= link_to "Roles", roles_path %></li>
      </ul>
    </li>
    <% else %>
    
    <li><%= link_to "Users", users_path %></li>
    <% end %>
		</li>
		<li><%= link_to "Conferences", conferences_path %></li>
		<li class="dropdown">
			<a class="dropdown-toggle"	data-toggle="dropdown" href="#">
				Countries
				<b class="caret"></b>
			</a>

			<ul class="dropdown-menu">
				<li><%= link_to "Custom Country Lists", lists_path %></li>
				<li><%= link_to "All Countries", countries_path %></li>
			</ul>
		</li>
		<li><%= link_to "Committees", committees_path %></li>
		<li class="active"><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>
<% else %>
<ul class="nav nav-tabs" style="padding-top:20px;">
		<li ><%= link_to "Conferences", conferences_path %></li>
		<li class="active"><%= link_to "Schools", schools_path %></li>
		<li><%= link_to "Delegates", delegates_path %></li>
	</li>
</ul>
<% end %>
<div class="pull-right">
	<%= form_for @search, :url => schools_path, :html => {:method => :get} do |f| %>
		<%= f.text_field :school_name_contains, :class => "navbar-search form-inline input-medium search-query", :placeholder => "Search" %>
	<% end %>
</div>
<h2>Schools</h2>
  
  <br/>

<div class="well form-inline">

<table class="table table-striped">
	<thead>
		<tr>
			<th>School name</th>
			<th>Conference</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @schools.each do |school| %>
		<tr>
			<td><%= link_to school.school_name, school %><br/>
				<%= school.school_address %></td>
			<td><%= school.conference.conference_title %></td>
			<td><%= link_to image_tag('trash.png'), [school.conference, school], :confirm => 'Are you sure you want to delete this school?', :method => :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

<br/><hr>

<p ALIGN="RIGHT"> <i class="icon-download-alt"></i> Export to <a href="http://localhost:3000/schools.xls"> excel</a> </p>
<p ALIGN="RIGHT"> <i class="icon-chevron-up"></i> <a href="#top">Back to Top</a></p>
</div>

app/views/schools/new.html.erb
<h3>Add a new school</h3>

<%= render 'form' %>

<button class="btn"><%= link_to 'Back', schools_path %></button>

app/views/schools/show.html.erb
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<div class="container">
<% if !current_user.role? :"MUN Director" %>
<ul class="nav nav-tabs" style="padding-top:20px; background-color:white; margin-bottom: 0px;">
    <% if current_user.role? "System Admin" %>
    <li class="dropdown">
      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
        Users
        <b class="caret"></b>
      </a>

      <ul class="dropdown-menu">
        <li><%= link_to "All Users", users_path %></li>
        <li><%= link_to "Roles", roles_path %></li>
      </ul>
    </li>
    <% else %>
    
    <li><%= link_to "Users", users_path %></li>
    <% end %>
    </li>
    <li><%= link_to "Conferences", conferences_path %></li>
    <li class="dropdown">
      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
        Countries
        <b class="caret"></b>
      </a>

      <ul class="dropdown-menu">
        <li><%= link_to "Custom Country Lists", lists_path %></li>
        <li><%= link_to "All Countries", countries_path %></li>
      </ul>
    </li>
    <li><%= link_to "Committees", committees_path %></li>
    <li class="active"><%= link_to "Schools", schools_path %></li>
    <li><%= link_to "Delegation Assignments", delegation_assignments_path %></li>
    <li><%= link_to "Delegates", delegates_path %></li>
  </li>
</ul>
<% else %>
<ul class="nav nav-tabs" style="padding-top:20px; background-color:white; margin-bottom: 0px;">
    <li ><%= link_to "Conferences", conferences_path %></li>
    <li class="active"><%= link_to "Schools", schools_path %></li>
    <li><%= link_to "Delegates", delegates_path %></li>
  </li>
</ul>
<% end %>
<!--when click on conference name-->
<section id="conference">
<div class="row-fluid">
<div class="span12 well" style="margin-top:20px; height:auto;">
        <h4>Registration for <%= @school.conference.conference_title %></h4>
        <hr>
        <h1><%= @school.school_name %></h1>
        <h3 style="color: #39b1c6;"><%= @school.school_address %></h3>
        <% if @school.countries != nil %>
        <a href="#createdelegate" role="button" class="btn" data-toggle="modal"><i class="icon-plus" style="padding-top:2px;"></i>&nbsp;Add Delegate</a>
        <% end %>

    </div>
</div>
<% for country in Country.btaschool(@school) %>
<div class="row-fluid">
      <div class="span12 well" style="height:auto;">
        
<table class="table table-striped">
  <thead>
              <th>Committee</th>
              <th>Delegate</th>
              <th>Date of Birth</th>
              <th>Gender</th>
              <th>Nationality</th>
              <th></th>
            </thead>
        
          <h3><%= country.country_name %></h3>


          <% for list in country.lists %>
            
            <tbody>
            <% for committee in list.committees %>
              <tr>
              
              <% for delegate in committee.delegates %>
              <td><%= committee.committee_name %></td>
                <td><%= link_to((delegate.fullname), delegate_path(delegate)) %></td>
                <td><%= delegate.date_of_birth.strftime('%b %d, %Y') %></td>
              <td><%= delegate.gender %></td>
              <td><%= delegate.nationality %></td>
              <td><%= link_to image_tag('trash.png'), [delegate.school, delegate], :confirm => 'Are you sure you want to delete this delegate?', :method => :delete %></td>
              </tr>
              <% end %>
              
              
              
            <% end %>
          </tbody>
          
          <% end %>
        
        </table>
        
      </div>
    </div>
    <% end %>

        <br/><br/>

        
        <div id="createdelegate" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add Delegate</h3>
  </div>
  <div class="modal-body">
    <%= render 'delegates/form' %>
  </div>
</div>

      </div>
    </div>